[project]
name = "microsfot-agent-framework"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
	"agent-framework-azure-ai",
	"agent-framework-openai",
	"agent-framework-core",
	"agent-framework-orchestrations",
	"opentelemetry-semantic-conventions",
	"opentelemetry-semantic-conventions-ai",
	"openai",
	"python-dotenv",
	#"monocle-apptrace",
]

[tool.uv.sources]
monocle-apptrace = { path = "monocle_apptrace-0.8.7b1-py3-none-any.whl" }
